services:
  backend:
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:change-me-strong-password@telemon-postgres-1:5432/telegram_messenger
    networks:
      - default
      - telemon_db_net

  frontend:
    networks:
      - default

  nginx:
    image: nginx:alpine
    environment:
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: .template
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /tmp/telegram-dashboard-backend/nginx/nginx-ssl.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - default

networks:
  telemon_db_net:
    external: true
