"""add AI platform tables (tools, workflows, tasks, events, schedules, plugins, providers)

Revision ID: 93d331972067
Revises: e1f2a3b4c5d6
Create Date: 2026-07-19 11:02:32.593038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93d331972067'
down_revision: Union[str, None] = 'e1f2a3b4c5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_api_call_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('request_body', sa.JSON(), nullable=True),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_api_call_logs_correlation_id'), 'ai_api_call_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_ai_api_call_logs_provider'), 'ai_api_call_logs', ['provider'], unique=False)
    op.create_index(op.f('ix_ai_api_call_logs_tenant_id'), 'ai_api_call_logs', ['tenant_id'], unique=False)
    op.create_table('ai_api_provider_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('api_base_url', sa.String(length=255), nullable=False),
    sa.Column('api_key_encrypted', sa.String(length=500), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('rate_limit_rpm', sa.Integer(), nullable=False),
    sa.Column('rate_limit_tpm', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_api_provider_configs_tenant_id'), 'ai_api_provider_configs', ['tenant_id'], unique=False)
    op.create_table('ai_event_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.Column('handler_count', sa.Integer(), nullable=False),
    sa.Column('handler_success_count', sa.Integer(), nullable=False),
    sa.Column('handler_failure_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_event_logs_correlation_id'), 'ai_event_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_ai_event_logs_created_at'), 'ai_event_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_event_logs_event_type'), 'ai_event_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_ai_event_logs_tenant_id'), 'ai_event_logs', ['tenant_id'], unique=False)
    op.create_table('ai_event_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('handler_type', sa.String(length=50), nullable=False),
    sa.Column('handler_ref', sa.String(length=255), nullable=False),
    sa.Column('filter_condition', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('retry_on_failure', sa.Boolean(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_event_subscriptions_event_type'), 'ai_event_subscriptions', ['event_type'], unique=False)
    op.create_index(op.f('ix_ai_event_subscriptions_tenant_id'), 'ai_event_subscriptions', ['tenant_id'], unique=False)
    op.create_table('ai_plugin_registrations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('plugin_type', sa.String(length=50), nullable=False),
    sa.Column('entry_point', sa.String(length=255), nullable=False),
    sa.Column('config_schema', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('provides_tools', sa.JSON(), nullable=True),
    sa.Column('provides_workflow_steps', sa.JSON(), nullable=True),
    sa.Column('provides_event_handlers', sa.JSON(), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_ai_plugin_registrations_tenant_id'), 'ai_plugin_registrations', ['tenant_id'], unique=False)
    op.create_table('ai_schedule_definitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_config', sa.JSON(), nullable=False),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=True),
    sa.Column('cron_expression', sa.String(length=100), nullable=True),
    sa.Column('run_at', sa.DateTime(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('max_executions', sa.Integer(), nullable=False),
    sa.Column('current_executions', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_schedule_definitions_tenant_id'), 'ai_schedule_definitions', ['tenant_id'], unique=False)
    op.create_table('ai_schedule_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('schedule_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_schedule_executions_schedule_id'), 'ai_schedule_executions', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_ai_schedule_executions_tenant_id'), 'ai_schedule_executions', ['tenant_id'], unique=False)
    op.create_table('ai_task_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_task_logs_task_id'), 'ai_task_logs', ['task_id'], unique=False)
    op.create_index(op.f('ix_ai_task_logs_tenant_id'), 'ai_task_logs', ['tenant_id'], unique=False)
    op.create_table('ai_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('schedule_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_tasks_created_at'), 'ai_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_tasks_priority'), 'ai_tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_ai_tasks_schedule_at'), 'ai_tasks', ['schedule_at'], unique=False)
    op.create_index(op.f('ix_ai_tasks_status'), 'ai_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_ai_tasks_task_type'), 'ai_tasks', ['task_type'], unique=False)
    op.create_index(op.f('ix_ai_tasks_tenant_id'), 'ai_tasks', ['tenant_id'], unique=False)
    op.create_table('ai_tool_definitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tool_type', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('handler_ref', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_tool_definitions_name'), 'ai_tool_definitions', ['name'], unique=True)
    op.create_index(op.f('ix_ai_tool_definitions_tenant_id'), 'ai_tool_definitions', ['tenant_id'], unique=False)
    op.create_table('ai_tool_execution_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('workflow_execution_id', sa.String(length=36), nullable=True),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('arguments', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_tool_execution_logs_session_id'), 'ai_tool_execution_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_ai_tool_execution_logs_task_id'), 'ai_tool_execution_logs', ['task_id'], unique=False)
    op.create_index(op.f('ix_ai_tool_execution_logs_tenant_id'), 'ai_tool_execution_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ai_tool_execution_logs_tool_name'), 'ai_tool_execution_logs', ['tool_name'], unique=False)
    op.create_index(op.f('ix_ai_tool_execution_logs_workflow_execution_id'), 'ai_tool_execution_logs', ['workflow_execution_id'], unique=False)
    op.create_table('ai_workflow_definitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('edges', sa.JSON(), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=True),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_workflow_definitions_name'), 'ai_workflow_definitions', ['name'], unique=False)
    op.create_index(op.f('ix_ai_workflow_definitions_tenant_id'), 'ai_workflow_definitions', ['tenant_id'], unique=False)
    op.create_table('ai_workflow_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('current_step', sa.String(length=100), nullable=True),
    sa.Column('progress_pct', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_workflow_executions_status'), 'ai_workflow_executions', ['status'], unique=False)
    op.create_index(op.f('ix_ai_workflow_executions_tenant_id'), 'ai_workflow_executions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ai_workflow_executions_workflow_id'), 'ai_workflow_executions', ['workflow_id'], unique=False)
    op.create_table('ai_workflow_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('step_id', sa.String(length=100), nullable=False),
    sa.Column('step_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_workflow_steps_execution_id'), 'ai_workflow_steps', ['execution_id'], unique=False)
    # ### end Alembic commands ###
    # NOTE: autogenerate also picked up spurious drops/alters for ai_chat_v2,
    # ai_reply_v2, admin_audit_logs, broadcasts, message_logs and payment_records —
    # artifacts of those model modules not being imported into alembic/env.py's
    # Base.metadata registration (a pre-existing gap, unrelated to this change).
    # Those were stripped from this migration; it only creates the new AI Platform
    # tables (tools/workflows/tasks/events/schedules/plugins/providers).


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_workflow_steps_execution_id'), table_name='ai_workflow_steps')
    op.drop_table('ai_workflow_steps')
    op.drop_index(op.f('ix_ai_workflow_executions_workflow_id'), table_name='ai_workflow_executions')
    op.drop_index(op.f('ix_ai_workflow_executions_tenant_id'), table_name='ai_workflow_executions')
    op.drop_index(op.f('ix_ai_workflow_executions_status'), table_name='ai_workflow_executions')
    op.drop_table('ai_workflow_executions')
    op.drop_index(op.f('ix_ai_workflow_definitions_tenant_id'), table_name='ai_workflow_definitions')
    op.drop_index(op.f('ix_ai_workflow_definitions_name'), table_name='ai_workflow_definitions')
    op.drop_table('ai_workflow_definitions')
    op.drop_index(op.f('ix_ai_tool_execution_logs_workflow_execution_id'), table_name='ai_tool_execution_logs')
    op.drop_index(op.f('ix_ai_tool_execution_logs_tool_name'), table_name='ai_tool_execution_logs')
    op.drop_index(op.f('ix_ai_tool_execution_logs_tenant_id'), table_name='ai_tool_execution_logs')
    op.drop_index(op.f('ix_ai_tool_execution_logs_task_id'), table_name='ai_tool_execution_logs')
    op.drop_index(op.f('ix_ai_tool_execution_logs_session_id'), table_name='ai_tool_execution_logs')
    op.drop_table('ai_tool_execution_logs')
    op.drop_index(op.f('ix_ai_tool_definitions_tenant_id'), table_name='ai_tool_definitions')
    op.drop_index(op.f('ix_ai_tool_definitions_name'), table_name='ai_tool_definitions')
    op.drop_table('ai_tool_definitions')
    op.drop_index(op.f('ix_ai_tasks_tenant_id'), table_name='ai_tasks')
    op.drop_index(op.f('ix_ai_tasks_task_type'), table_name='ai_tasks')
    op.drop_index(op.f('ix_ai_tasks_status'), table_name='ai_tasks')
    op.drop_index(op.f('ix_ai_tasks_schedule_at'), table_name='ai_tasks')
    op.drop_index(op.f('ix_ai_tasks_priority'), table_name='ai_tasks')
    op.drop_index(op.f('ix_ai_tasks_created_at'), table_name='ai_tasks')
    op.drop_table('ai_tasks')
    op.drop_index(op.f('ix_ai_task_logs_tenant_id'), table_name='ai_task_logs')
    op.drop_index(op.f('ix_ai_task_logs_task_id'), table_name='ai_task_logs')
    op.drop_table('ai_task_logs')
    op.drop_index(op.f('ix_ai_schedule_executions_tenant_id'), table_name='ai_schedule_executions')
    op.drop_index(op.f('ix_ai_schedule_executions_schedule_id'), table_name='ai_schedule_executions')
    op.drop_table('ai_schedule_executions')
    op.drop_index(op.f('ix_ai_schedule_definitions_tenant_id'), table_name='ai_schedule_definitions')
    op.drop_table('ai_schedule_definitions')
    op.drop_index(op.f('ix_ai_plugin_registrations_tenant_id'), table_name='ai_plugin_registrations')
    op.drop_table('ai_plugin_registrations')
    op.drop_index(op.f('ix_ai_event_subscriptions_tenant_id'), table_name='ai_event_subscriptions')
    op.drop_index(op.f('ix_ai_event_subscriptions_event_type'), table_name='ai_event_subscriptions')
    op.drop_table('ai_event_subscriptions')
    op.drop_index(op.f('ix_ai_event_logs_tenant_id'), table_name='ai_event_logs')
    op.drop_index(op.f('ix_ai_event_logs_event_type'), table_name='ai_event_logs')
    op.drop_index(op.f('ix_ai_event_logs_created_at'), table_name='ai_event_logs')
    op.drop_index(op.f('ix_ai_event_logs_correlation_id'), table_name='ai_event_logs')
    op.drop_table('ai_event_logs')
    op.drop_index(op.f('ix_ai_api_provider_configs_tenant_id'), table_name='ai_api_provider_configs')
    op.drop_table('ai_api_provider_configs')
    op.drop_index(op.f('ix_ai_api_call_logs_tenant_id'), table_name='ai_api_call_logs')
    op.drop_index(op.f('ix_ai_api_call_logs_provider'), table_name='ai_api_call_logs')
    op.drop_index(op.f('ix_ai_api_call_logs_correlation_id'), table_name='ai_api_call_logs')
    op.drop_table('ai_api_call_logs')
    # ### end Alembic commands ###
