"""add scheduled_at to broadcasts

Revision ID: 9c3a947ed6e0
Revises: 4f9cbbe5b062
Create Date: 2026-07-03 18:15:28.334465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c3a947ed6e0'
down_revision: Union[str, None] = '4f9cbbe5b062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broadcasts', sa.Column('scheduled_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_broadcasts_scheduled_at'), 'broadcasts', ['scheduled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_broadcasts_scheduled_at'), table_name='broadcasts')
    op.drop_column('broadcasts', 'scheduled_at')
    # ### end Alembic commands ###
